// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using u21503193_HW02.Data;

#nullable disable

namespace u21503193_HW02.Migrations
{
    [DbContext(typeof(DBPetContext))]
    [Migration("20230923104025_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("u21503193_HW02.Models.Adoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdoptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("Adoptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdoptionDate = new DateTime(2023, 9, 23, 12, 40, 25, 500, DateTimeKind.Local).AddTicks(1381),
                            PetId = 1,
                            UserId = 0,
                            UserName = "John"
                        },
                        new
                        {
                            Id = 2,
                            AdoptionDate = new DateTime(2023, 9, 23, 12, 40, 25, 500, DateTimeKind.Local).AddTicks(1387),
                            PetId = 2,
                            UserId = 0,
                            UserName = "Jane"
                        },
                        new
                        {
                            Id = 3,
                            AdoptionDate = new DateTime(2023, 9, 23, 12, 40, 25, 500, DateTimeKind.Local).AddTicks(1389),
                            PetId = 3,
                            UserId = 0,
                            UserName = "Michael"
                        },
                        new
                        {
                            Id = 4,
                            AdoptionDate = new DateTime(2023, 9, 23, 12, 40, 25, 500, DateTimeKind.Local).AddTicks(1391),
                            PetId = 4,
                            UserId = 0,
                            UserName = "Emily"
                        },
                        new
                        {
                            Id = 5,
                            AdoptionDate = new DateTime(2023, 9, 23, 12, 40, 25, 500, DateTimeKind.Local).AddTicks(1393),
                            PetId = 5,
                            UserId = 0,
                            UserName = "David"
                        },
                        new
                        {
                            Id = 6,
                            AdoptionDate = new DateTime(2023, 9, 23, 12, 40, 25, 500, DateTimeKind.Local).AddTicks(1395),
                            PetId = 6,
                            UserId = 0,
                            UserName = "Sarah"
                        });
                });

            modelBuilder.Entity("u21503193_HW02.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PetStory")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            Breed = "Labrador",
                            CreatedDate = new DateTime(2023, 9, 23, 12, 40, 25, 500, DateTimeKind.Local).AddTicks(1091),
                            Gender = "Male",
                            ImageUrl = "/images/pet1.jpg",
                            Location = "Gauteng",
                            Name = "Buddy",
                            PetStory = "Buddy is a friendly Labrador looking for a loving home. He enjoys long walks and playing fetch.",
                            Status = "Available",
                            Type = "Dog",
                            UserId = 1,
                            Weight = 25.0m
                        },
                        new
                        {
                            Id = 2,
                            Age = 1,
                            Breed = "Siamese",
                            CreatedDate = new DateTime(2023, 9, 23, 12, 40, 25, 500, DateTimeKind.Local).AddTicks(1117),
                            Gender = "Female",
                            ImageUrl = "/images/pet2.jpg",
                            Location = "Cape Town",
                            Name = "Whiskers",
                            PetStory = "Whiskers is a playful Siamese cat with a sweet disposition. She loves cuddling and chasing toy mice.",
                            Status = "Adopted",
                            Type = "Cat",
                            UserId = 2,
                            Weight = 10.0m
                        },
                        new
                        {
                            Id = 3,
                            Age = 3,
                            Breed = "Golden Retriever",
                            CreatedDate = new DateTime(2023, 9, 23, 12, 40, 25, 500, DateTimeKind.Local).AddTicks(1122),
                            Gender = "Male",
                            ImageUrl = "/images/pet3.jpg",
                            Location = "Durban",
                            Name = "Rocky",
                            PetStory = "Rocky is an energetic Golden Retriever who enjoys outdoor adventures and fetching tennis balls.",
                            Status = "Available",
                            Type = "Dog",
                            UserId = 3,
                            Weight = 30.0m
                        },
                        new
                        {
                            Id = 4,
                            Age = 2,
                            Breed = "Persian",
                            CreatedDate = new DateTime(2023, 9, 23, 12, 40, 25, 500, DateTimeKind.Local).AddTicks(1127),
                            Gender = "Female",
                            ImageUrl = "/images/pet4.jpg",
                            Location = "Cape Town",
                            Name = "Mittens",
                            PetStory = "Mittens is a graceful Persian cat known for her luxurious fur and elegant demeanor.",
                            Status = "Available",
                            Type = "Cat",
                            UserId = 4,
                            Weight = 12.0m
                        },
                        new
                        {
                            Id = 5,
                            Age = 1,
                            Breed = "Dachshund",
                            CreatedDate = new DateTime(2023, 9, 23, 12, 40, 25, 500, DateTimeKind.Local).AddTicks(1132),
                            Gender = "Female",
                            ImageUrl = "/images/pet5.jpg",
                            Location = "Gauteng",
                            Name = "Charlie",
                            PetStory = "Charlie is a playful Dachshund who loves going on adventures and meeting new people.",
                            Status = "Adopted",
                            Type = "Dog",
                            UserId = 5,
                            Weight = 15.0m
                        },
                        new
                        {
                            Id = 6,
                            Age = 2,
                            Breed = "Cockatiel",
                            CreatedDate = new DateTime(2023, 9, 23, 12, 40, 25, 500, DateTimeKind.Local).AddTicks(1137),
                            Gender = "Male",
                            ImageUrl = "/images/pet6.jpg",
                            Location = "Durban",
                            Name = "Kiwi",
                            PetStory = "Kiwi is a colorful Cockatiel with a cheerful personality. He enjoys singing and mimicking sounds.",
                            Status = "Available",
                            Type = "Bird",
                            UserId = 6,
                            Weight = 0.2m
                        });
                });

            modelBuilder.Entity("u21503193_HW02.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FirstName = "Emily",
                            LastName = "Johnson",
                            PhoneNumber = "0611111111"
                        },
                        new
                        {
                            UserId = 2,
                            FirstName = "David",
                            LastName = "Smith",
                            PhoneNumber = "0712222222"
                        },
                        new
                        {
                            UserId = 3,
                            FirstName = "Sophia",
                            LastName = "Brown",
                            PhoneNumber = "0813333333"
                        },
                        new
                        {
                            UserId = 4,
                            FirstName = "Oliver",
                            LastName = "Davis",
                            PhoneNumber = "0614444444"
                        },
                        new
                        {
                            UserId = 5,
                            FirstName = "Ava",
                            LastName = "Wilson",
                            PhoneNumber = "0715555555"
                        },
                        new
                        {
                            UserId = 6,
                            FirstName = "Lucas",
                            LastName = "Miller",
                            PhoneNumber = "0816666666"
                        });
                });

            modelBuilder.Entity("u21503193_HW02.Models.Adoption", b =>
                {
                    b.HasOne("u21503193_HW02.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("u21503193_HW02.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("u21503193_HW02.Models.Pet", b =>
                {
                    b.HasOne("u21503193_HW02.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
